export const POST = {
  FETCH_POSTS_PENDING: "FETCH_POSTS_PENDING",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  CREATE_POST_PENDING: "CREATE_POST_PENDING",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
  UPDATE_POST_PENDING: "UPDATE_POST_PENDING",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",
  DELETE_POST_PENDING: "DELETE_POST_PENDING",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
}

export const DIALOG = {
  OPEN_DIALOG: "OPEN_DIALOG",
  CLOSE_DIALOG: "CLOSE_DIALOG",
  CONFIRM_DIALOG: "CONFIRM_DIALOG",
  CANCEL_DIALOG: "CANCEL_DIALOG"
}
